# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='like',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
