# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180621_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
